name: Build WSL Tarball
description: 'Build a WSL tarball for a given system configuration'
inputs:
  config:
    description: 'System configuration to build'
    required: true
  filename:
    description: 'Filename to save the image as'
    required: true


runs:
  using: 'composite'  
  steps:
    - name: Build tarball builder 🛠️
      id: buildBuilder
      uses: ./.github/actions/build-nix-expression
      with:
        expression: '.#nixosConfigurations.${{ inputs.config }}.config.system.build.tarballBuilder'

    - name: Build tarball 📦
      shell: bash
      env:
        FILENAME: ${{ inputs.filename }}
        DRV: ${{ steps.buildBuilder.outputs.derivation }}
      run: sudo "${DRV}/bin/nixos-wsl-tarball-builder" "$FILENAME"
