name: Generate Version
description: 'Generates a version number based on the GitHub event context'
outputs:
  version:
    description: 'The generated version number'
    value: ${{ steps.version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Generate Version 🏷️
      id: version
      shell: pwsh
      env:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: |
        if ('$env:GITHUB_EVENT_NAME' -eq 'pull_request') {
          $version = 'pr-${{ github.event.pull_request.number }}'
          $is_numeric = ''
        } elseif ('$env:GITHUB_REF_NAME' -like 'release-*') {
          $latest_tag = git describe --tags --abbrev=0
          $commit_count = git rev-list --use-bitmap-index --count "$(git rev-list --tags --no-walk --max-count=1)..HEAD"
          $version = "$($latest_tag -replace '(.+)\.(.+)\.(.+)\..+', '$1.$2.$3').${commit_count}"
          $is_numeric = 1
        } else {
          $version = '$env:GITHUB_REF_NAME'
          $is_numeric = ''
        }
        "version=$version" | Tee-Object -FilePath $env:GITHUB_OUTPUT -Append
        "is_numeric=$is_numeric" | Tee-Object -FilePath $env:GITHUB_OUTPUT -Append

    - name: Set Version 🏷️
      shell: pwsh
      env:
        VERSION: ${{ steps.version.outputs.version }}
      run: |
        Write-Output "$env:VERSION" | Tee-Object -FilePath ./VERSION
        Write-Output "$(git rev-parse HEAD)" | Tee-Object -FilePath ./VERSION -Append
