name: On Command

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  parse:
    name: Check Permissions and Parse Command ⌨️
    runs-on: ubuntu-latest
    outputs:
      command: ${{ steps.command.outputs.command }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Get actor permissions
        id: check-permissions
        continue-on-error: true
        uses: prince-chrismc/check-actor-permissions-action@d504e74ba31658f4cdf4fcfeb509d4c09736d88e # v3.0.2
        with:
          permission: write

      - name: Log actor permissions
        run: |
          echo Actor has permission: ${{ steps.check-permissions.outputs.permitted && ' true' || 'false' }}
          echo Actor is bot user:    ${{ github.actor == 'nixos-wsl-bot' && ' true' || 'false' }}

      - name: Post error message if not permitted
        if: ${{ !steps.check-permissions.outputs.permitted && github.actor != 'nixos-wsl-bot' }}
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          pr-number: ${{ inputs.pr_number || github.event.issue.number }}
          message: |
            You do not have permission to run this command @${{ github.actor }}.

      - name: Stop if not permitted
        if: ${{ !steps.check-permissions.outputs.permitted && github.actor != 'nixos-wsl-bot' }}
        run: |
          exit 1

      - name: Parse command
        id: command
        if: steps.check-permissions.outputs.permitted || github.actor == 'nixos-wsl-bot'
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          echo "$COMMENT_BODY" | sed -nE 's|^/([a-z0-9\-]+)|command=\1|p' >> $GITHUB_OUTPUT

  trigger-on-push:
    name: Trigger Push Workflow 🚀
    needs: parse
    if: needs.parse.outputs.command == 'run-ci' && github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Get PR branch
        id: branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "branch=$(gh pr view ${{ github.event.issue.number }} --json headRefName -q .headRefName)" >> $GITHUB_OUTPUT

      - name: Dispatch workflow
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          BRANCH: ${{ steps.branch.outputs.branch }}
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'on_push.yml',
              ref: process.env.BRANCH,
              inputs: {
                pr_number: context.issue.number.toString(),
                post_result: 'true'
              }
            })
